#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# continously take data and print the rate every few seconds
# last edit July-21, 2022 (EOC)
#
# example execute:
# ./macros/read_igor_rga_file --NeventsMax=10 --no-email
#

import sys, os, linecache, pandas as pd
import glob
import argparse

parser = argparse.ArgumentParser(description='read RGA data file')
parser.add_argument("--Nruns",        type=int, default=1,
                    required=False, help="number of runs to process ('-1' for all runs)")
parser.add_argument("--FirstRun",     type=int, default=0,
                    required=False, help="first run to start from")
parser.add_argument("--NeventsMax",   type=int, default=-1,
                    required=False, help="maximal number of events to process")
parser.add_argument("--fdebug",       type=int, default=1,
                    required=False, help="verbosity")
parser.add_argument("--PrintProgress",type=int, default=50000,
                    required=False, help="print progress (every N events)")
parser.add_argument("--no-email",   dest="no_email",
                    default=False,  required=False,
                    action='store_true', help="do not send email")
parser.add_argument("--FirstEvent",     type=int, default=0,
                    required=False, help="first event to start from")
parser.add_argument("--worker",       type=str, default="ErezMBP",
                    required=False, help="worker: Erez-ifarm/ErezMBP")


args = parser.parse_args()

Nruns         = args.Nruns
NeventsMax    = args.NeventsMax
fdebug        = args.fdebug
PrintProgress = args.PrintProgress
FirstRun      = args.FirstRun
FirstEvent    = args.FirstEvent


path          = "";
if args.worker == "Erez-ifarm": #{
    data_path = r'/volatile/clas12/users/ecohen/BAND/RGA_Free_proton'
#}
elif args.worker == "ErezMBP": #{
    data_path = r'/Users/erezcohen/Desktop/data/BAND/RGA_Free_proton'
#}



filenames     = ["ntupleNew"];

for runIdx in range(len(filenames)):#{

    filename = filenames[runIdx]
    commandline = ("root -l -q 'ReadIgorRGAFile.C(\"%s\",%d,%d,%d,\"%s\")'"%
                    (filename,NeventsMax,fdebug,PrintProgress,data_path))
    print('')
    print("processing file %s"%(filename))
    print('')
    print(commandline)
    print('')

    os.system( commandline )
    if (runIdx >= Nruns): break;
#}

print('')
print('done.')
print('')
#if args.no_email==False:#{
#    mailtitle = 'Done processing skim_sidis_multiple_runs on ifarm'
#    mailbody  = 'e.g. scp -r cohen@ftp.jlab.org:/volatile/clas12/users/ecohen/BAND/SIDIS_skimming/skimmed_SIDIS_inc_006420_e_piplus_selected_eepi_kinematics.csv \~/Desktop/data/BAND/SIDIS_skimming/'
#    emailstr = ('echo %s | mail -s "%s" cohen.erez7@gmail.com'%(mailbody,mailtitle) )
#    os.system(emailstr)
##}
