#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
from multiprocessing.sharedctypes import Value
import sys, os, linecache
import argparse
from subprocess import Popen, PIPE

parser = argparse.ArgumentParser(description='SIDIS skimming of multiple runs')
parser.add_argument("--Nruns",        type=int, default=-1,
                    required=False, help="number of runs to process ('-1' for all runs)")
parser.add_argument("--FirstRun",     type=int, default=0,
                    required=False, help="first run to start from")
parser.add_argument("--NeventsMax",   type=int, default=-1,
                    required=False, help="maximal number of events to process")
parser.add_argument("--fdebug",       type=int, default=0,
                    required=False, help="verbosity")
parser.add_argument("--PrintProgress",type=int, default=500000,
                    required=False, help="print progress (every N events)")
parser.add_argument("--Neutrons",     type=int, default=0,
                    required=False, help="tagged (1) or untagged (0)")
args = parser.parse_args()

Nruns         = args.Nruns
NeventsMax    = args.NeventsMax
fdebug        = args.fdebug
PrintProgress = args.PrintProgress
FirstRun      = args.FirstRun
Neutrons      = args.Neutrons
outfilepath   = "/volatile/clas12/users/akiral/BAND/"
runs_filename = "/work/clas12/users/akiral/SIDIS_at_BAND/macros/runlists/good_runs_10-2.txt"
txt_dir       = "/volatile/clas12/users/akiral/BAND/txt_files"
skimmer       = "/work/clas12/users/akiral/SIDIS_at_BAND/CppAnalysis/MCPionRatios.C"
pion_codes    = [211, -211]

if Neutrons:
    skimmer = "/work/clas12/users/akiral/SIDIS_at_BAND/CppAnalysis/TaggedRatios.C"


# Using readlines()
runs_file = open(runs_filename, 'r')
run_fileLines = runs_file.readlines()
if Nruns<0: Nruns = len(run_fileLines)
if fdebug>1:#{
    print('good runs to process:')
    #for line in run_fileLines[FirstRun:]:#{
    #    print(int(line.strip()), end =" ")
    #}
    print('')
    print('processing %d runs, starting from run %d'%(Nruns-FirstRun,FirstRun))
#}


runIdx = 0
for line in run_fileLines[FirstRun:]:#{
    runIdx += 1
    run = int(line.strip())
    run_str = str(run).zfill(6)


    for pion_code in pion_codes:
        pion_type = ""
        if pion_code == 211:
            pion_type = "plus"
        elif pion_code == -211:
            pion_type = "minus"
        else:
            raise ValueError("Unknown Pion code: " + str(pion_code))

        infilename  = os.path.join(outfilepath, "SIDIS_skimming", "skimmed_SIDIS_inc_" + run_str + "_e_pi" + pion_type + ".root")
        outfilename = os.path.join(outfilepath, "histograms", "pion_ratio_" + run_str + "_" + pion_type + ".root")

        commandline = """#!/bin/sh
    #SBATCH --job-name=h{0}
    #SBATCH -p production
    #SBATCH --account=clas12
    #SBATCH --time=60
    #SBATCH --constraint=centos77
    #SBATCH --mem-per-cpu=1000
    #SBATCH --output={6}/hist_{0}.txt
    root -l -q '{7}({1},{2},{3},"{4}","{5}")'
    """.format(run, NeventsMax, pion_code, Neutrons, infilename, outfilename, txt_dir, skimmer)
        print('')
        print("processing run %d/%d/%d"%(runIdx,Nruns,pion_code))
        print('')
        print(commandline)
        print('')
        
        p=Popen(args=["sbatch"],stdin=PIPE)
        p.communicate(commandline.encode())
    
#    os.system( commandline )
    if (runIdx >= Nruns): break;
#}

print('')
print('done.')
print('')

# MCPionRatios(Int_t NeventsMax=-1, Int_t pionCode=211, Int_t neutrons=0, TString infilename="", TString outfileName="")
