#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# continously take data and print the rate every few seconds
# last edit Apr-28, 2021 (EOC)
#
import sys, os, linecache
import argparse

parser = argparse.ArgumentParser(description='SIDIS skimming of multiple runs')
parser.add_argument("--Nruns",        type=int, default=-1,
                    required=False, help="number of runs to process ('-1' for all runs)")
parser.add_argument("--FirstRun",     type=int, default=0,
                    required=False, help="first run to start from")
parser.add_argument("--fdebug",       type=int, default=1,
                    required=False, help="verbosity")
parser.add_argument("--no-email",   dest="no_email",
                    default=False,  required=False,
                    action='store_true', help="do not send email")
                                

args = parser.parse_args()

Nruns         = args.Nruns
fdebug        = args.fdebug
FirstRun      = args.FirstRun
runs_filename = "macros/runlists/good_runs_10-2-final.txt"

# Using readlines()
runs_file = open(runs_filename, 'r')
run_fileLines = runs_file.readlines()
if Nruns<0: Nruns = len(run_fileLines)
if fdebug>1:#{
    print('good runs to process:')
    for line in run_fileLines[FirstRun:]:#{
        print(int(line.strip()), end =" ")
    #}
    print('')
    print('processing %d runs, starting from run %d'%(Nruns-FirstRun,FirstRun))
#}

runIdx = 0
for line in run_fileLines[FirstRun:]:#{
    runIdx += 1
    run = int(line.strip())
    commandline = ("clas12root -l -q 'ReadBeamCharge.C+(%d,%d)'"%
                    (run,fdebug))
    print('')
    print("processing run %d/%d"%(runIdx,Nruns))
    print('')
    print(commandline)
    print('')
    
    os.system( commandline )
    if (runIdx >= Nruns): break;
#}

print('')
print('done.')
print('')
if args.no_email==False:#{
    mailtitle = 'Done processing read_beam_charge on ifarm'
    mailbody  = ''
    emailstr = ('echo %s | mail -s "%s" cohen.erez7@gmail.com'%(mailbody,mailtitle) )
    os.system(emailstr)
#}
