#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# read GEMC simulation results for the production of pion acceptance maps
# last edit May-12, 2022 (EOC)
#
# example execute:
# ./macros/read_gemc_pion_acceptance --NeventsMax=100000 --fdebug=1 --only-pi+
# ./macros/read_gemc_pion_acceptance --NeventsMax=10 --fdebug=5 --only-pi+

import sys, os, linecache
import argparse

parser = argparse.ArgumentParser(description='Read GEMC simulation results - pion acceptance maps')
parser.add_argument("--NeventsMax",     type=int, default=-1,
                    required=False, help="maximal number of events to process")
parser.add_argument("--fdebug",         type=int, default=1,
                    required=False, help="verbosity")
parser.add_argument("--PrintProgress",  type=int, default=50000,
                    required=False, help="print progress (every N events)")
parser.add_argument("--filelabel",      type=str, default="p_uniform_distribution",
                    required=False, help="options: \n p_uniform_distribution \n p_uniform_distribution_default \ p_uniform_distribution_rgb_spring2019")
parser.add_argument("--no-email",   dest="no_email",
                    default=False,  required=False,
                    action='store_true', help="do not send email")


parser.add_argument('--only-pi+',   dest='only_pips', action='store_true', help="do only pi+ (and not pi-)")


args = parser.parse_args()

NeventsMax    = args.NeventsMax
fdebug        = args.fdebug
PrintProgress = args.PrintProgress
filelabel     = args.filelabel

pi_charges = ['pips','pims']
if args.only_pips: #{
    pi_charges    = ['pips']
#}

for pi_charge in pi_charges:#{
    commandline = ("clas12root -q 'Read_PiAcceptance_GEMCimulations.C+(\"%s\",%d,%d,%d,\"%s\")'"%
                    (pi_charge,NeventsMax,fdebug,PrintProgress,filelabel))
    print('')
    print("Readind %s acceptance simulations"%(pi_charge))
    print('')
    print(commandline)
    print('')
    os.system( commandline )
#}

print('')
print('done.')
print('')

if args.no_email==False:#{
    os.system('date | mail -s "Done processing read_gemc_pion_acceptance on ifarm" cohen.erez7@gmail.com')
#}
