#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# read GEMC simulation results for the production of pion acceptance maps
# last edit Jan-19, 2022 (EOC)
#
import sys, os, linecache
import argparse

parser = argparse.ArgumentParser(description='Read GEMC simulation results - pion acceptance maps')
parser.add_argument("--NeventsMax",   type=int, default=-1,
                    required=False, help="maximal number of events to process")
parser.add_argument("--fdebug",       type=int, default=1,
                    required=False, help="verbosity")
parser.add_argument("--PrintProgress",type=int, default=50000,
                    required=False, help="print progress (every N events)")
args = parser.parse_args()

NeventsMax    = args.NeventsMax
fdebug        = args.fdebug
PrintProgress = args.PrintProgress

runIdx = 0
for piCharge in ['pips','pims']:#{
    commandline = ("clas12root -q 'Read_PiAcceptance_GEMCimulations.C+(\"%s\",%d,%d,%d)'"%
                    (piCharge,NeventsMax,fdebug,PrintProgress))
    print('')
    print("Readind %s acceptance simulations"%(piCharge))
    print('')
    print(commandline)
    print('')
    os.system( commandline )
#}

print('')
print('done.')
print('')

os.system('date | mail -s "Done processing read_gemc_pion_acceptance on ifarm" cohen.erez7@gmail.com')
