#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# continously take data and print the rate every few seconds
# last edit Sep-12, 2021 (EOC)
#
import sys, os, linecache
import argparse

parser = argparse.ArgumentParser(description='SIDIS skimming of multiple runs')
parser.add_argument("--Nruns",        type=int, default=1,
                    required=False, help="number of runs to process ('-1' for all runs)")
parser.add_argument("--FirstRun",     type=int, default=0,
                    required=False, help="first run to start from")
parser.add_argument("--NeventsMax",   type=int, default=-1,
                    required=False, help="maximal number of events to process")
parser.add_argument("--fdebug",       type=int, default=1,
                    required=False, help="verbosity")
parser.add_argument("--PrintProgress",type=int, default=50000,
                    required=False, help="print progress (every N events)")
args = parser.parse_args()

Nruns         = args.Nruns
NeventsMax    = args.NeventsMax
fdebug        = args.fdebug
PrintProgress = args.PrintProgress
FirstRun      = args.FirstRun
runs_filename = "macros/runlists/good_runs_10-2.txt"

# Using readlines()
runs_file = open(runs_filename, 'r')
run_fileLines = runs_file.readlines()
if Nruns<0: Nruns = len(run_fileLines)
if fdebug>1:#{
    print('good runs to process:')
    for line in run_fileLines[FirstRun:]:#{
        print(int(line.strip()), end =" ")
    #}
    print('')
    print('processing %d runs, starting from run %d'%(Nruns-FirstRun,FirstRun))
#}

runIdx = 0
for line in run_fileLines[FirstRun:]:#{
    runIdx += 1
    run = int(line.strip())
    commandline = ("clas12root -q 'SIDISc12rSkimmer.C+(%d,%d,%d,%d)'"%
                    (run,NeventsMax,fdebug,PrintProgress))
    print('')
    print("processing run %d/%d"%(runIdx,Nruns))
    print('')
    print(commandline)
    print('')
    
    os.system( commandline )
    if (runIdx >= Nruns): break;
#}

print('')
print('done.')
print('')

emailstr = ('date | mail -s "Done processing skim_sidis_multiple_runs on ifarm" cohen.erez7@gmail.com'
        +
        'e.g.\n'
        +
        'scp -r cohen@ftp.jlab.org:/volatile/clas12/users/ecohen/BAND/SIDIS_skimming/skimmed_SIDIS_inc_006420_e_piplus_selected_eepi_kinematics.csv ~/Desktop/data/BAND/SIDIS_skimming/')
os.system(emailstr)
