#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# continously take data and print the rate every few seconds
# last edit June-23, 2023 (EOC)
#
# execute:
#
# skim_sidis_specific_file
# skim_sidis_specific_file --NeventsMax=10 --fdebug=3
# skim_sidis_specific_file --fdebug=3

import sys, os, linecache
import argparse

parser = argparse.ArgumentParser(description='SIDIS skimming of multiple runs')
parser.add_argument("--NeventsMax",   type=int, default=-1,
                    required=False, help="maximal number of events to process")
parser.add_argument("--fdebug",       type=int, default=1,
                    required=False, help="verbosity")
parser.add_argument("--PrintProgress",type=int, default=500000,
                    required=False, help="print progress (every N events)")
parser.add_argument("--no-email",   dest="no_email",
                    default=False,  required=False,
                    action='store_true', help="do not send email")
parser.add_argument("--FirstEvent",     type=int, default=0,
                    required=False, help="first event to start from")
parser.add_argument("--Skimming",     type=str, default="SIDIS_skimming",
                    required=False,
                    help="SIDIS_skimming, RGA_Free_proton, p_uniform_distribution" )
parser.add_argument("--FilePath",     type=str, default="/work/clas12/ecohen/mc/sidis/he3",
                    required=False,
                    help="file path")
parser.add_argument("--Ebeam",     type=float, default=10.6,
                    required=False, help="beam energy")
parser.add_argument("--Filename",     type=str, default="MC_clasdis.neutron",
                    required=False,
                    help="file name")

parser.add_argument("--only-pi+",        dest="only_pips",
                    default=False,
                    action='store_true', help="do only pi+ (and not pi-)")
parser.add_argument("--inclusive",          dest="inclusive",
                    type=int,               default=0,
                    help="do not apply cuts")


args = parser.parse_args()

NeventsMax    = args.NeventsMax
fdebug        = args.fdebug
PrintProgress = args.PrintProgress
FirstEvent    = args.FirstEvent
Skimming      = args.Skimming
FilePath      = args.FilePath
Filename      = args.Filename
Ebeam         = args.Ebeam


print('')
print("Analyzing specific file:",FilePath,"/",Filename)
print('')
commandline = ("clas12root -q 'SIDISc12rSkimmer.C+(0,%d,%d,%d,%d,\"%s\",\"\",%f,\"\",\"\",\"\",%d,\"%s\",\"%s\")'"%
                    (NeventsMax,fdebug,PrintProgress,FirstEvent,Skimming,Ebeam,args.inclusive,FilePath,Filename))
print(commandline)
os.system( commandline )
    
print('')
print('------------------------------------------------------------')
print('')
print('done.')
print('')
if args.no_email==False:#{
    mailtitle = 'Done processing skim_sidis_multiple_runs on ifarm'
    mailbody  = ('Processed %s - %d runs, see /volatile/clas12/users/ecohen/BAND/%s/'%( DataPath, Nruns, Skimming))
    emailstr = ('echo %s | mail -s %s cohen.erez7@gmail.com'%(mailbody,mailtitle) )
    os.system(emailstr)
#}
