#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# continously take data and print the rate every few seconds
# last edit Sep-12, 2021 (EOC)
#
import sys, os, linecache
import argparse
from subprocess import Popen, PIPE

parser = argparse.ArgumentParser(description='SIDIS skimming of multiple runs')
parser.add_argument("--Nruns",        type=int, default=-1,
                    required=False, help="number of runs to process ('-1' for all runs)")
parser.add_argument("--FirstRun",     type=int, default=0,
                    required=False, help="first run to start from")
parser.add_argument("--NeventsMax",   type=int, default=-1,
                    required=False, help="maximal number of events to process")
parser.add_argument("--fdebug",       type=int, default=0,
                    required=False, help="verbosity")
parser.add_argument("--PrintProgress",type=int, default=500000,
                    required=False, help="print progress (every N events)")
args = parser.parse_args()

Nruns         = args.Nruns
NeventsMax    = args.NeventsMax
fdebug        = args.fdebug
PrintProgress = args.PrintProgress
FirstRun      = args.FirstRun
runs_filename = "/work/clas12/users/akiral/SIDIS_at_BAND/macros/runlists/good_runs_10-2.txt"
txt_dir       = "/volatile/clas12/users/akiral/BAND/txt_files"
skimmer       = "/work/clas12/users/akiral/SIDIS_at_BAND/MCSIDISc12rSkimmer.C"
input_dir     = "/volatile/clas12/rg-b/production/recon/spring2019/torus-1/pass1/v0/dst/train_20200610/inc/"
outfilepath   = "/volatile/clas12/users/akiral/BAND/SIDIS_skimming/"


# Using readlines()
runs_file = open(runs_filename, 'r')
run_fileLines = runs_file.readlines()
if Nruns<0: Nruns = len(run_fileLines)
if fdebug>1:#{
    print('good runs to process:')
    for line in run_fileLines[FirstRun:]:#{
        print(int(line.strip()), end =" ")
    #}
    print('')
    print('processing %d runs, starting from run %d'%(Nruns-FirstRun,FirstRun))
#}


runIdx = 0
for line in run_fileLines[FirstRun:]:#{
    runIdx += 1
    run = int(line.strip())
    run_str = str(run).zfill(6)
    input_path = os.path.join(input_dir, "inc_" + run_str + ".hipo")
    outfilename = "skimmed_SIDIS_inc_" + run_str

    commandline = """#!/bin/sh
#SBATCH --job-name=s{0}
#SBATCH -p production
#SBATCH --account=clas12
#SBATCH --time=60
#SBATCH --mem-per-cpu=1000
#SBATCH --output={7}/sidis_{0}.txt
clas12root -q '{8}+({1},{2},{3},1,"{4}","{5}","{6}")'
""".format(run, NeventsMax, fdebug, PrintProgress, input_path, outfilepath, outfilename, txt_dir, skimmer)
    print('')
    print("processing run %d/%d"%(runIdx,Nruns))
    print('')
    print(commandline)
    print('')
    
    p=Popen(args=["sbatch"],stdin=PIPE)
    p.communicate(commandline.encode())
    
#    os.system( commandline )
    if (runIdx >= Nruns): break;
#}

print('')
print('done.')
print('')
